### PR TITLE
using location.protocol instead of hard-coded 'http://'

### PR DESCRIPTION
**Pull request by mikeplavsky**
When hosting fitnesse behind https proxy such features as tooltips and sidebar do not work because of hard-coded http protocol.

### CODE REVIEW

**Comment by mikeplavsky** [comment]
Found the error in the code

**Comment by mikeplavsky** [comment]
But actually it should work because the changed code returns string: 
location.protocol + '//'  is equal to "https://" or "http://"

**Comment by mikeplavsky** [comment]
Yep, I have checked the current master (462080d8fc2c634b5) , it is RED - the same errors @konstantinvlasenko ^

**Comment by rbastiaansen732** [comment]
I would also like this improvement for the same kind of reason, that FitNesse is running behind a Nginx proxy that is doing https->http ssl offloading.

**Comment by tcnh** [comment]
Completely missed this one. Sorry guys! Will have a look now!

**Pull request merged**
